server:
  port: 8083            #访问端口
  servlet:
    context-path: /iedFileSend   #访问路径 http://localhost:8083/ied/
    jsp:
      init-parameters:
        development: true
spring:
  profiles:
    active: dev
  devtools:
    restart:
      enabled: true #设置热部署开启
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
  thymeleaf:
    cache: false
    mode: HTML5
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
  application:
    name: ufls
#  kafka:
#    bootstrap-servers: 192.175.1.21:9092
##    bootstrap-servers: 192.168.31.11:9092
#    #provider
#    producer:
#      retries: 10 #在发送失败时，重试10次
#      #每批次发送消息的数量
#      batch-size: 1000
#      buffer-memory: 1000000
#      #指定消息key value的编解码格式
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#    #consumer
#    #指定消费者group id
#    consumer:
#      group-id: ied-cime-group1
#      auto-offset-reset: latest
#      enable-auto-commit: true
#      auto-commit-interval: 100
#      #指定消息key value的编解码格式
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  redis:
    database: 0
    host: 127.0.0.1
    password:
    jedis:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 1000
    port: 6379