server:
  port: 8087            #访问端口
  servlet:
    context-path: /ied   #访问路径 http://localhost:8080/ied/
    jsp:  #jsp支持
      init-parameters:
        development: true
spring:
  profiles:
#    include: data
  devtools:
    restart:
      enabled: true #设置热部署开启
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
  thymeleaf:
    cache: false
    mode: HTML5
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
  application:
    name: ied
  datasource:
#    url: jdbc:dm://127.0.0.1:5236?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    url: jdbc:dm://192.175.1.21:5236?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: SYSDBA
    password: SYSDBA
    type: com.alibaba.druid.pool.DruidDataSource
##    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: dm.jdbc.driver.DmDriver
#    filters: stat
#    maxActive: 20
#    initialSize: 1
#    maxWait: 60000
#    minIdle: 1
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: select 'x'
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    poolPreparedStatements: true
#    maxOpenPreparedStatements: 20
  kafka:
    bootstrap-servers: 192.175.1.21:9092
    producer:
      retries: 10 #在发送失败时，重试10次
      #每批次发送消息的数量
      batch-size: 1000
      buffer-memory: 1000000
      #指定消息key value的编解码格式
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: ied-web-group
      auto-offset-reset: latest
      enable-auto-commit: true
      auto-commit-interval: 100
      #指定消息key value的编解码格式
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#  redis:
#    database: 0
#    host: 127.0.0.1
#    password:
#    jedis:
#      pool:
#        max-active: 20
#        max-wait: -1
#        max-idle: 10
#        min-idle: 0
#    timeout: 1000
#    port: 6379
#  profiles:
#    active: spring  #spring为application-spring.yml文件名的添加部分（加载外部yml文件）
mybatis:
  mapper-locations: classpath:mapper/*.xml  #classpath就是应用程序resources的路径
  type-aliases-package: com.kedong.ieduflswebcommon.entity #自定义的扫描实体类
  configuration:
    lazy-loading-enabled: true #配置懒加载
    aggressive-lazy-loading: false #配置属性懒加载
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印所有sql
logging:
  level:
    com.kedong.iedweb.dao: debug
pagehelper:
#  helper-dialect: informix
  helper-dialect: dm
#  reasonable: true
